#! /bin/zsh

quotes=(
'May your blade always be wet, and powder dry.'
'Under a black flag we sail and the sea shall be our empire.'
'Ahoy matey! Let’s trouble the water!'
'Under a black flag we shall sail.'
'Obey the captain or learn to swim.'
'I be ruler of the seven seas!'
'Shiver me timbers!'
'Obey the captain or learn to swim.'
'I be ruler of the seven seas!'
'Shiver me timbers!'
'Avast, ye scurvy dog.'
'Walk the plank, ye scallywag.'
'Pillage and plunder.'
'Batten down the hatches.'
'Weigh anchor and hoist the mizzen.'
'Here be treasure, matey.'
'Thar she blows!'
'Yo ho ho and a bottle of rum.'
'Prepare to be boarded.'
'May your anchor be tight, your cork be loose, your rum be spiced and your compass be true.'
'Loot is first and wimmen second. Because if ye have the first ye’ll have the second, but if ye have the second ye won’t have the first for long!'
'The rougher the seas, the smoother we sail. Ahoy!'
'No cause is lost if there is but one fool left to fight for it.'
'Avast ye landlubbers! Ye can throw ye lunch in Davy Jones’ locker, but not yer homework!'
'Every generation welcomes the pirates from the last. — Lawrence Lessig'
'Life’s pretty good, and why wouldn’t it be? I’m a pirate, after all. — Johnny Depp'
'But I don’t want to be a pirate. — Jerry Seinfeld'
'To life, love and loot. — Captain Morgan'
'Why join the navy if you can be a pirate? — Steve Jobs'
'A merry life and a short one shall be my motto. — Bartholomew Roberts'
'It is a glorious thing To be a Pirate King. — W. S. Gilbert'
'Not all treasure’s silver and gold, mate. — Jack Sparrow, Pirates of the Caribbean'
'When a pirate grows rich enough, they make him a prince. — George R R Martin'
'It is when pirates count their booty that they become mere thieves. — William Bolitho'
'Now and then we had a hope that if we lived and were good, God would permit us to be Pirates. — Mark Twain'
'Where there is a sea there are pirates. — Greek proverb'
'There is nothing so desperately monotonous as the sea, and I no longer wonder at the cruelty of pirates. — James Russell Lowell'
'Land was created to provide a place for boats to visit. — Brooks Atkinson'
'Damnation seize my soul if I give you quarters, or take any from you. — Blackbeard'
'Even pirates, before they attack another ship, hoist a black flag. — Bela Kiraly'
'In politics and in trade, bruisers and pirates are of better promise than talkers and clerks. — Ralph Waldo Emerson'
'I am a man of fortune and must seek my fortune. — Captain Henry Every'
'Waves crack with wicked fury against me ship’s hull while ocean currents rage as the full moon rises o’re the sea. — Captain John Phillips'
'In an honest service, there is thin commons, low wages, and hard labor. — Black Bart'
'If you’d fought like a man, you would not have been hang’d like a dog. — Anne Bonny'
'Heaven, you fool? Did you ever year of any pirates going thither? Give me hell, it’s a merrier place. — Thomas Sutton'
)

card() {
    local ranks suits r s
    ranks=( A 2 3 4 5 6 7 8 9 J Q K )
    suits=( ♠ ♥ ♦ ♣ )
    r=$ranks[$(( ${RANDOM} % $#ranks + 1 ))]
    s=$suits[$(( ${RANDOM} % $#suits + 1 ))]
    print $r$s
}

qi=$(( ${RANDOM} % $#quotes + 1 ))
quote=$quotes[$qi]
color=$(( ${RANDOM} % 256 + 1 ))
c=$(card)

print
print  "\x1b[48;5;${color}m      \e[0m"
print  "\x1b[48;5;${color}m  $c  \e[0m  $quote"
print  "\x1b[48;5;${color}m      \e[0m"
print
