#! /bin/zsh

# Detect if input file is missing a newline at end of file
# https://unix.stackexchange.com/a/542520/101165

# Why it matters:
# - https://gist.github.com/OleksiyRudenko/d51388345ea55767b7672307fe35adf3
# - https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

print "\n\nin missingnewline: $@ \n\n"

allok=true
nlcheck() {
    filename=$1
    if [ ! -s "$filename" ]; then
        echo "$filename is empty"
    elif [ -z "$(tail -c 1 <"$filename")" ]; then
        : echo "$filename ends with a newline or with a null byte"
    else
        echo "$filename does not end with a newline nor with a null byte"
        echo "How to configure your editor: https://gist.github.com/OleksiyRudenko/d51388345ea55767b7672307fe35adf3"
        unset allok
    fi
}

for f in $@; do nlcheck $f; done

if [[ -z $allok ]]; then
    # print 'Found probs, exiting non-zero'
    exit 1
fi
